import type { BrandProfile } from "../exam/types";

export const brandProfiles: BrandProfile[] = [
  {
    id: "brand_stonyhurst_internal",
    name: "Stonyhurst",
    mode: "stonyhurst",
    logoAssetId: null,
    primaryColour: "#1f2f5f",
    accentColour: "#b5892a",
    documentHeaderText: "Exam Foundry",
    documentFooterText: "For internal use only - Stonyhurst",
    internalBuildLabel: "Stonyhurst Internal Build",
    enabled: true,
  },
  {
    id: "brand_neutral_internal",
    name: "Neutral",
    mode: "neutral",
    logoAssetId: null,
    primaryColour: "#2f3437",
    accentColour: "#527c67",
    documentHeaderText: "Exam Foundry",
    documentFooterText: "For internal use only",
    internalBuildLabel: "Internal Build",
    enabled: true,
  },
  {
    id: "brand_custom_placeholder",
    name: "Custom",
    mode: "custom",
    logoAssetId: null,
    primaryColour: "#3a3732",
    accentColour: "#7c6f5c",
    documentHeaderText: "Exam Foundry",
    documentFooterText: "Custom branding is planned for a later version",
    internalBuildLabel: "Internal Build",
    enabled: false,
  },
];
