import type { BrandProfile, DataPack, PaperDraft, PaperTemplate, ValidationState } from "../exam/types";

export type PaperExportFormat = "pdf";
export type ExportImplementationStatus = "planned";

export interface PaperExportContext {
  brandProfile: BrandProfile;
  dataPack: DataPack;
  draft: PaperDraft;
  template: PaperTemplate;
  validationState: ValidationState;
}

export interface PaperExportOptions {
  format: PaperExportFormat;
  includeCrest: boolean;
  includeSpecificationCode: boolean;
}

export interface PaperPreviewResult {
  status: ExportImplementationStatus;
  title: string;
  message: string;
}

export interface PaperExportResult {
  status: "blocked" | ExportImplementationStatus;
  message: string;
  reasons: string[];
}

export interface PaperExportService {
  preparePreview: (context: PaperExportContext) => Promise<PaperPreviewResult>;
  exportPaper: (context: PaperExportContext, options: PaperExportOptions) => Promise<PaperExportResult>;
}

export interface ExportPreparationState {
  canPreview: boolean;
  canExport: boolean;
  statusLabel: "Ready" | "Blocked";
  primaryReason: string;
  blockingReasons: string[];
  warningReasons: string[];
  implementationStatus: ExportImplementationStatus;
}

export const createExportPreparationState = (validationState: ValidationState): ExportPreparationState => {
  const blockingReasons =
    validationState.exportReadiness.reasons.length > 0
      ? validationState.exportReadiness.reasons
      : validationState.blockingErrors.map((error) => error.label);
  const warningReasons = validationState.warnings.map((warning) => warning.label);
  const canExport = validationState.exportReadiness.isReady;

  return {
    canPreview: true,
    canExport,
    statusLabel: canExport ? "Ready" : "Blocked",
    primaryReason: canExport
      ? "PDF export is ready for the future export service."
      : (blockingReasons[0] ?? "Resolve Paper Health issues before exporting."),
    blockingReasons,
    warningReasons,
    implementationStatus: "planned",
  };
};

export const plannedPaperExportService: PaperExportService = {
  preparePreview: async (context) => ({
    status: "planned",
    title: context.draft.title,
    message: "Paper preview will be generated by the export service in a later milestone.",
  }),
  exportPaper: async (context) => {
    const exportPreparation = createExportPreparationState(context.validationState);

    if (!exportPreparation.canExport) {
      return {
        status: "blocked",
        message: "PDF export is blocked by paper validation.",
        reasons: exportPreparation.blockingReasons,
      };
    }

    return {
      status: "planned",
      message: "PDF export will be generated by the export service in a later milestone.",
      reasons: [],
    };
  },
};
